<template>
  <v-container>
    <h1>About a-delivery</h1>
    <v-row>
    	<h3 class="mt-3 mb-1" id="basics">The Basics</h3>
    	<p class="text-left">This website scrapes order confirmation emails sent from grubhub, delivery.com,
    		ChowNow, ToastTab, Brandibble, and Gloriafood.com with the help of a bot. Once the data in the confirmation emails are scraped, it will be saved to a database and be accesible by whoever has the permissions to view them.
    	</p>
    </v-row>

    <v-row>
    	<p class="text-left">
    		To begin, you'll need a code given to you by the website administrator. This code will allow you to
    		create an account at <router-link :to="'signup'">this address</router-link> with the application
    		permissions neccesary to link a gmail account to the application. If you already have an account,
    		click <router-link :to="'node'">here</router-link> to give us access to your gmail account.
    	</p>
    </v-row>

    <v-row>
    	<h3 class="mt-3 mb-1" id="detail">A Little More Detail</h3>
    	<p class="text-left">
    		When you create an account on this website with the secret code given to you by the admin, your account is created with owner and manager permissions. In short, these permissions allow you to create a business account. To your business account, you can add managers and partners. </p>
    </v-row>
    <v-row>
    	<p class="text-left">
    		If you have co-workers within your business who you trust with dispatch responsibilities, you can allow them to join the website as a manager of you business account. They will have permission to read your order data, but they won't be able to edit them, nor will they be allowed to change the private information of your business account.
    	</p>
    </v-row>

    <v-row>
    	<p class="text-left">
    		So what are partners? The bot, as it stands right now, will try to connect the data from the confirmation email, to a partner you have registered in our database. So a partner would simply be a restaurants you are partnered with. Though this might not be neccesary, I went ahead with this decision because the data will be far more informative in the end.
    	</p>
    </v-row>

    <v-row>
    	<p class="text-left">
    		For example, with this set up, you will be able to see the portion of revenue generated by each of you partners in detail and with ease. In order to make this possible, you will have to add partners to your business account. You can do this easily
    		<router-link :to="'partners'">right here at this link</router-link> once you have your account setup.
    	</p>
    </v-row>


    <v-row>
    	<h3 class="mt-3 mb-1" id="security">Your Privacy and Security</h3>
    	<p class="text-left">For reasons of practicality and safety, it would be best for you to not use your everyday gmail account. Create a new one if you can. Our application will have access to all emails of the account you link us, and will also modify the labels of your account's emails. If you don't want a bot messing with your inbox, we reccomend you use a dummy email address.</p>
    </v-row>

    <v-row>
    	<p class="text-left">
    		Furthermore, your privacy is very important to us. We guarentee you that the bot will never have any kind of malicious code in it scraping your personal data. However, we still strongly urge you not to ever give us the chance; you can do that by creating a dummy gmail account.
    	</p>
    </v-row>

    <v-row>
    	<h3 class="mt-3 mb-1" id="gmail">The Bot</h3>
    	<p class="text-left">
    		Lets delve a bit deeper into how the bot works: once you give the bot access to your gmail account(hopefully not your everyday one!), the bot will periodically send a request to gmail's servers to check to see whether new confirmation emails have been sent to it. Who will send these confirmation emails? That is you! You must forward emails from your real inbox, to the gmail account you give us permission to read and modify. <strong>Important!</strong> It is very important that when you create your business account <router-link :to="'node'">here,</router-link> you remember that the email field on the form must be the email address doing the forwarding <i>to</i> the gmail account you link us. If this confuses you, just ask the site admin. 
    	</p>
    </v-row>

    <v-row>
    	<h3 class="mt-3 mb-1">Features Coming In the Future</h3>
    	<p class="text-left">
    		Currently there's no use for adding workers to you business account. Not until we can perfect the bot. But in the future, you will be able to assign orders to your workers through the website. Web push notifications and instant chat are certainly in the works...but lets finnish the bot first.
    	</p>
    </v-row>
  </v-container>
</template>
